### PR TITLE
Polishing, hopefully finalising, the vignette

### PR DESCRIPTION
**Pull request by Robinlovelace**
This is a placeholder - any comments/suggestions on my work welcome

### CODE REVIEW

**Comment by mpadge** [comment]
is this ready to merge? Or is there more to come?

**Comment by Robinlovelace** [comment]
More to come.

**Comment by mpadge** [comment]
thanks heaps robin! and with due apology, you'll also need to merge the master again. the good news is that i've added examples for all functions, so that task is now done. with your vignette work, we should then be finished! let me know when the PR is ready

**Comment by Robinlovelace** [comment]
No problem Mark - just merged your latest version, seems to be OK. As I say, any feedback on this welcome - will get on to substance now, promise!

**Comment by Robinlovelace** [comment]
Any idea why the CI is failing?

**Comment by mpadge** [comment]
it's not from what i see. The main branch is passing, and it says here that your branch passes too.

**Comment by Robinlovelace** [comment]
Passing now - indeed.

**Comment by Robinlovelace** [comment]
Another question: why were you not running the seville example code? Ran locally, line by line, and it failed (object name mismatches) - have set it to run again and tried to make it more explicit. Think that's an improvement from the code and readability perspective. Any feedback welcome though.

**Comment by mpadge** [comment]
I wasn't running any of the vignette code simply because as i said the API servers are not 100%, and any fails on their part lead to `R CMD check` failures and ultimately CRAN failures. There's no real need to run them, and it's definitely much safer *not* to.

**Comment by Robinlovelace** [comment]
Fair reasoning.

**Comment by Robinlovelace** [comment]
Sorry to say: this is all I can do today - there's more to do that I thought!

That's a good thing: still need to get the relations example in there and fix the running code to make it not run again...

**Comment by Robinlovelace** [comment]
Happy for you to accept this as is or just wait for me to get through the whole thing. Feedback of course welcome.

**Comment by Robinlovelace** [comment]
One idea: create an `on_cran` boolean at the outset and run if not. Thoughts? It's nice to run stuff - the 1st seville example was still running btw I think - happy to not run anything though as intended..

**Comment by mpadge** [comment]
The `on_cran` boolean will then fail to compile the CRAN vignettes properly, so i don't think that can really be used. I'll have a look through this arvo and accept the PR before you go any further.

**Comment by Robinlovelace** [comment]
I'll go one better and `rebase`!

**Comment by mpadge** [comment]
nice job with the vignette. just one wee request: could you please wrap all lines to 80 characters? (I've just pushed those changes myself this time.)

**Comment by Robinlovelace** [comment]
Sure  and good practice.

**Pull request merged**
