### PR TITLE
Polishing vignette

### PR DESCRIPTION
**Pull request by Robinlovelace**

### CODE REVIEW

**Comment by mpadge** [comment]
Can you please remove the `toc: true` from the now very short README.Rmd?

**Comment by Robinlovelace** [comment]
Sure

**Comment by mpadge** [comment]
Hey by the way, you've got admin here, so you can just ` gut remote origin osmdata ` and push straight there

**Comment by Robinlovelace** [comment]
Aye, that's: `git push up master` for me. Kinda in the habit of PRs now.

**Pull request merged**
